# Generated by Django 3.1.5 on 2022-02-14 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.TextField()),
                ('description', models.TextField()),
                ('dateCreation', models.DateField()),
                ('dateActualisation', models.DateField()),
                ('latitudeLieuTravail', models.IntegerField()),
                ('longitudeLieuTravail', models.IntegerField()),
                ('entreprise', models.TextField()),
                ('typeContrat', models.TextField()),
                ('experienceExigee', models.TextField()),
                ('salaire', models.TextField()),
                ('dureeTravail', models.TextField()),
                ('rythmeTravail', models.TextField()),
                ('alternance', models.TextField()),
                ('nomContact', models.TextField()),
                ('qualification', models.TextField()),
                ('qualitesPro', models.TextField()),
                ('origineOffre', models.TextField()),
            ],
        ),
    ]
