# Generated by Django 3.1.5 on 2022-02-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pole',
            name='latitudeLieuTravail',
            field=models.TextField(default='Non renseigné'),
        ),
        migrations.AlterField(
            model_name='pole',
            name='longitudeLieuTravail',
            field=models.TextField(default='Non renseigné'),
        ),
    ]
